library(xlsx)
library(lubridate)
library(tidyverse)


#' Inserted into a TryCatch to write a function to an Error log
#' 
#' @error  An error generated by tryCatch
#' @pipeline  A pipelinename, presumably provided in a config file
#' @writeLocation  A folder location to write errors to.
#' @returns an excel spreadsheet of errors.  This spreadsheet is either
#'          created at the time the error is collected, or appended to
#'          and existing sheet.  Rows:
#'          timestamp: Timestamp for error -- written in UTC
#'          error: Error code returned from tryCatch
#'          pipeline: Pipeline name.


writeErrorDataFrame <- function(
      error
    , pipeline
    , writeLocation
){
  # write initial data
  data <- list(
    timestamp   = c(lubridate::now(tzone = 'UTC') %>% format('%Y.%m.%d %H:%M:%S'))
    , error     = c(error)
    , pipeline  = c(pipeline)
  )
  
  # Write to Dataframe
  df <- do.call(
    cbind
    , data
  ) %>%
    as.data.frame %>%
    mutate_all(as.character)
  
  
  # Generate log File name:
  fileName_log <- paste(
    writeLocation
    , '/errorLog.xlsx'
    , sep = ''
  )
  
  # Check for excel file:
  if(file.exists(fileName_log)){
    
    # if file name does exits, read file and concatenate
    logFile <- xlsx::read.xlsx(
      fileName_log
      , sheetName = "ErrorSheets"
    ) %>%
      rbind(
        df
      )
    
    # Rewrite file.
    xlsx::write.xlsx(
      logFile
      , paste(
        writeLocation
        , '/errorLog.xlsx'
        , sep = ''
      )
      , row.names = FALSE
      , sheetName = "ErrorSheets"
    )
  } else {
    
    # if file doesn't exist, write to file
    xlsx::write.xlsx(
      df
      , paste(
        writeLocation
        , '/errorLog.xlsx'
        , sep = ''
      )
      , row.names = FALSE
      , sheetName = "ErrorSheets"
    )
  }
  
  
  print("log file written")
  
  
}